const BAD_REQUEST_CODE = 400;

const NOT_FOUND_CODE = 404;

const INTERNAL_SERVER_CODE = 500;

const CONFLICT_CODE = 409;

const FORBIDDEN_CODE = 403;

module.exports = {
  BAD_REQUEST_CODE,
  NOT_FOUND_CODE,
  INTERNAL_SERVER_CODE,
  CONFLICT_CODE,
  FORBIDDEN_CODE,
};
